
project_id = "vrzortmvycmkawbjbbdi"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[functions.send-account-welcome]
verify_jwt = false

[functions.check-expiring-accounts]
verify_jwt = false

[functions.send-renewal-notification]
verify_jwt = false

[edge_runtime]
enabled = true
port = 54323
inspector_port = 54324

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"
