// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrzortmvycmkawbjbbdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyem9ydG12eWNta2F3YmpiYmRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTU2NTYsImV4cCI6MjA2MzU5MTY1Nn0.V1s6oSdLEtDqvzovPp2fbGkN2pURiRp2HIK7m9liKYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);